# Generated by Django 4.1.3 on 2022-11-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_for_current_product',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
