# Generated by Django 4.1.3 on 2022-11-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_cart_total_for_current_product_cart_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
